### ISSUE TITLE
Collate pangolin output

### ISSUE THREAD

**Issue by pbiology** [genomic-medicine-sweden/gms-artic#10]
**What needs to be done:**
Collect and concatenate the output from Pangolin.
Right now all resultfiles from Pangolin lands in the top folder of the output directory. There is also a single file per sample being generated.
These should be gathered in a new place and then concatenated together to have a single easy to access output.

**Suggestions on how to get it done:**
- Create a specific output folder for pangolin files
- Concatenate all files together
- Modify the output from pangolin so the headers correspond to some specified output, perhaps this should be modelled on the FOHm directives for what they should look like.
- This could be part of the collate step

**What are the arguments for getting it done:**
- Cleaner output and easier to directly process them further in things like upload to various external partners such as FOHM.

**Comment by pbiology** [comment]
Perhaps this is solved now? What do you think @JD2112 ?

**Comment by JD2112** [comment]
> Perhaps this is solved now? What do you think @JD2112 ?

Yes, I think it's done! Sorry for late reply :)
