### ISSUE TITLE
Use GMS-Artic images through dockerhub

### ISSUE THREAD

**Issue by sylvinite** [genomic-medicine-sweden/gms-artic#4]
**What needs to be done:**
Images built under https://github.com/genomic-medicine-sweden/gms-artic/blob/master/scripts/build_singularity_containers.sh should have a fallback to pull them from dockerhub

- [x] Set up Dockerhub account
- [x] Set up solution to push images to Dockerhub (github actions)
- [x] Set up solution to pull images from dockerhub 
- [x] Automatically update the container on the local work directory

**Suggestions on how to get it done:**
Dockerhub, remote build

**What are the arguments for getting it done:**
The reason for running singularity is usually the exact same reason as to why its not possible to build images with the same account

**Comment by talnor** [comment]
Do we have a dockerhub account set up?

**Comment by talnor** [comment]
nextflow automatically pulls images from Dockerhub if we set process.container = "<dockerhub-user>/<image>" for singularity.

**Comment by JD2112** [comment]
`
singularity 
{    
singularity.enabled = true     
singularity.autoMounts = true
    if ( params.medaka || params.nanopolish ){    
 // process.container = "file:///${baseDir}/artic-ncov2019-nanopore.sif"     
// process.container = "docker://quay.io/jd2112/gms-artic:nanopore"      
process.container = "library://jd2112/gms-artic-illumina/gms-artic-nanopore.sif:latest"    
} else if (params.illumina) {    
 // process.container = "file:///${baseDir}/artic-ncov2019-illumina.sif"     
// process.container = "docker://quay.io/jd2112/gms-artic:illumina"      
process.container = "library://jd2112/gms-artic-illumina/gms-artic-illumina.sif:latest"    
}`

I add both docker hub container and singularity library container to the config file.
