### ISSUE TITLE
The CLI option --scheme-directory does nothing

### ISSUE THREAD

**Issue by sylvinite** [genomic-medicine-sweden/gms-artic#46]
**What needs to be done:**
The CLI option --scheme-directory needs to overwrite what is posted in the config

**Suggestions on how to get it done:**
Review the currently working options. Copy paste.

**What are the arguments for getting it done:**
Intuitively CLI options take precedence over config options

**Task is considered finished when:**
The CLI option --scheme-directory does what is intuitively expected

**Comment by JD2112** [comment]
Issues #46 

## WHAT has done
1. Changed the base.config file; now primer sets will be downloaded from the genomic-medicine-sweden repo instead artic-network/primer-schemes
2. Default primer set is - midnight V1
3. Primer set for each protocol added separately to the repo. Artic nanopolish cannot handle '/' in the repo name.

## HOW to use CLI-option
1. --scheme-directory artic-primer/V3/.
2. README updated - how to use --scheme-directory.

**Comment by JD2112** [comment]
Updates issue #46

1. --scheme required to run the pipeline.
2.  --scheme will add the primers from the repo list.
3.  Details of use can be found on README.
