### ISSUE TITLE
Muscle needs to be downgraded for nanopore analyses

### ISSUE THREAD

**Issue by henningonsbring** [genomic-medicine-sweden/gms-artic#54]
Today I downloaded the latest nanopore and pangolin containers from dockerhub to run an analysis of nanopore data. When running gms-artic the analysis crashed. To problem is that muscle is upgraded (and I don't understand how that happened). See error for the step where I get stuck:
```
singularity exec artic-ncov2019-nanopore.sif muscle -in kindcorgi_220410-154114_barcode15.muscle.in.fasta -out kindcorgi_220410-154114_barcode15.muscle.out.fasta


Invalid command line
Unknown option in
```

I tried to fix this error with this [PR](https://github.com/genomic-medicine-sweden/gms-artic/pull/47), but it did not work. In PR linked in last sentence the problem is also described in more detail.

**What needs to be done:**
Downgrade muscle to 3.8

**What are the arguments for getting it done:**
Needed to run analysis of nanopore data with medaka

**Task is considered finished when:**
It is possible to run analysis of nanopore data with medaka

**Comment by sofstam** [comment]
I tried to replicate this issue with: 

`singularity pull artic-ncov2019-nanopore.sif docker://genomicmedicinesweden/gms-artic-nanopore:latest`

and then I ran:

`singularity exec artic-ncov2019-nanopore.sif muscle`

I get the following:
<img width="1147" alt="Screenshot 2022-04-10 at 22 17 17" src="https://user-images.githubusercontent.com/91951607/162638136-d93055ff-1956-4a44-9f8f-d22097107667.png">

**Comment by sofstam** [comment]
This seems to be solved. I am closing this issue.

**Comment by henningonsbring** [comment]
yes, it is solved
