### ISSUE TITLE
Run pangolin on concatinated consensus file

### ISSUE THREAD

**Issue by sylvinite** [genomic-medicine-sweden/gms-artic#6]
**What needs to be done:**
Currently pangolin is ran on individual consensus files.
Pangolin needs to be ran on a concatinated consensus file.

**Suggestions on how to get it done:**
Change the input stream in the nextflow script

**What are the arguments for getting it done:**
Building a report function afterwards kind of requires it.
It is cleaner to do it like this than to build it into the report itself

**Task is considered finished when:**
There's a single pangolin file for a batch project that encompasses all samples

**Comment by pbiology** [comment]
In terms of scale, perhaps it would be better to keep the pangolin jobs separate, and then concatenate all results in the final collate step of the pipeline?

**Comment by sylvinite** [comment]
Sounds good
